/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExportPdfRouteImport } from './routes/export-pdf'
import { Route as SlidesIndexRouteImport } from './routes/slides.$index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportPdfRoute = ExportPdfRouteImport.update({
  id: '/export-pdf',
  path: '/export-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesIndexRoute = SlidesIndexRouteImport.update({
  id: '/slides/$index',
  path: '/slides/$index',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export-pdf': typeof ExportPdfRoute
  '/slides/$index': typeof SlidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export-pdf': typeof ExportPdfRoute
  '/slides/$index': typeof SlidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export-pdf': typeof ExportPdfRoute
  '/slides/$index': typeof SlidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/export-pdf' | '/slides/$index'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/export-pdf' | '/slides/$index'
  id: '__root__' | '/' | '/export-pdf' | '/slides/$index'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportPdfRoute: typeof ExportPdfRoute
  SlidesIndexRoute: typeof SlidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export-pdf': {
      id: '/export-pdf'
      path: '/export-pdf'
      fullPath: '/export-pdf'
      preLoaderRoute: typeof ExportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides/$index': {
      id: '/slides/$index'
      path: '/slides/$index'
      fullPath: '/slides/$index'
      preLoaderRoute: typeof SlidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportPdfRoute: ExportPdfRoute,
  SlidesIndexRoute: SlidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
